backend:
  name: github
  repo: gabecreates/api-test

media_folder: media_folder

collections:
  - name: post
    label: Post
    folder: "site/posts"
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
