backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "site/assets/uploads"

collections:
  - name: residentialProject
    label: Residential Project
    folder: "data/residential-projects"
    create: true
    fields:
      - {name: projectName, label: Project Name}
      - {name: featuredImage, label: Featured Image, widget: image}
      - {name: logoImage, label: Logo, widget: image}
      - {name: location, label: Location}
      - {name: city, label: City}
      - {name: status, label: Project Status, widget: select, options: [Coming Soon, Construction, Completed]}
      - {name: units, label: Number of Units}
      - {name: projectType, label: Project Type, widget: select, options: [High-rise Residential, Low-rise Residential, Commercial]}
      - {name: contactPhoneNumber, label: Contact Phone Number}
      - {name: contactEmail, label: Contact Email}
      - {name: websiteLink, label: Website Link, required: false}
      - {name: architect, label: Architect}
      - {name: interiorDesigner, label: Interior Designer}
      - {name: landscapeArchitect, label: Landscape Architect}
      - {name: description, label: Description, widget: text}
      - {name: exteriorGallery, label: Exterior Images, required: false, widget: list, fields: [{name: image, label: Image, widget: image}, {name: title, label: Title}]}
      - {name: interiorGallery, label: Interior Images, required: false, widget: list, fields: [{name: image, label: Image, widget: image}, {name: title, label: Title}]}
  - name: commercialProject
    label: Commercial Project
    folder: "data/commercial-projects"
    create: true
    fields:
      - {name: projectName, label: Project Name}
      - {name: location, label: Location}
      - {name: city, label: City}
      - {name: projectType, label: Project Type, widget: select, options: [Office, Mixed Use]}
      - {name: contactEmail, label: Contact Email}
      - {name: contactPhoneNumber, label: Contact Phone Number}
  - name: salesCentre
    label: Sales Centre
    folder: "data/sales-centres"
    create: true
    fields:
      - {name: title, label: Title}
      - {name: location, label: Location}
      - {name: city, label: City}
      - {name: hours, label: Hours, widget: list, fields: [{name: hoursItem}]}
      - {name: contactPhoneNumber, label: Contact Phone Number}
      - {name: contactEmail, label: Contact Email}
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.md"
        name: homePage
        label: Home Page
        fields:
          - {name: tagline, label: Tagline}
          - name: firstFeaturedProject
            label: First Featured Project
            widget: relation
            collection: residentialProject
            searchFields: [projectName]
            valueField: projectName
          - name: secondFeaturedProject
            label: Second Featured Project
            widget: relation
            collection: residentialProject
            searchFields: [projectName]
            valueField: projectName
          - name: thirdFeaturedProject
            label: Third Featured Project
            widget: relation
            collection: residentialProject
            searchFields: [projectName]
            valueField: projectName
          - {name: greenTagline, label: Green Tagline}
          - {name: greenText, label: Green Text, widget: text}
          - name: firstGreenProject
            label: First Green Project
            widget: relation
            collection: residentialProject
            searchFields: [title]
            valueField: title
          - name: secondGreenProject
            label: Second Green Project
            widget: relation
            collection: residentialProject
            searchFields: [projectName]
            valueField: projectName
          - name: thirdGreenProject
            label: Third Green Project
            widget: relation
            collection: residentialProject
            searchFields: [projectName]
            valueField: projectName
      - file: "data/pages/about.md"
        name: aboutPage
        label: About Page
        fields:
          - {name: quote, label: Quote, widget: text}
          - {name: quoteAuthor, label: Quote Author}
          - {name: aboutTagline, label: About Tagline}
          - {name: aboutText, label: About Text, widget: text}
          - {name: futureTagline, label: Future Tagline}
          - {name: futureText, label: Future Text}
